name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # branche contenant vos sources Jekyll

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Setup Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Install bundler and dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build --config _config.yml

    - name: Deploy to GitHub Pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Jeton intégré automatiquement
        publish_dir: ./_site
        publish_branch: gh-pages  # branche de publication Pages
